### ISSUE TITLE
Fixed type with defaults generate incorrect code.

### ISSUE THREAD

**Issue by zimbabao** [actgardner/gogen-avro#101]
Field in a record
```    "fields": [
        {
            "name": "ID",
            "type": {
                "type": "fixed",
                "size": 8,
                "name": "unsignedlong"
            },
            "default": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
        }
```
Ganerates type

```
type Unsignedlong [8]byte
```

But the generated is
```r.ID = []byte("\x00\x00\x00\x00\x00\x00\x00\x00")```
Where type of `r.ID` is `Unsignedlong`.

Go compiler fails to compile this.

**Comment by actgardner** [comment]
Thanks for reporting this @zimbabao! This should be resolved on master now, and I'll tag a new release this weekend with the fix. If the issue isn't resolved or you run into anything else feel free to open a new issue.
