### ISSUE TITLE
Provide a mechanism to convert from string to enum.

### ISSUE THREAD

**Issue by MrJoy** [actgardner/gogen-avro#104]
For enums, there's a generated `String()` method to convert an instance of the enum to the human-friendly string, but there's no analogous mechanism to go the other way.  The end result is that if I'm synthesizing a record to serialize to Avro from an external data source, I have to handle the mapping myself.  Not hard, but it _is_ brittle.  Can we get a generated method that wraps up the relevant switch operation so that logic is always in sync with the enum itself?

**Comment by actgardner** [comment]
Sorry for the slow response! This sounds like a useful feature, I can try and work on it this weekend. Otherwise I would also welcome a PR that added this functionality.

**Comment by MrJoy** [comment]
@actgardner I'll take a look, but I suspect it'll take me longer to wrap my head around the data model and Go code generation stuff that I won't be able to get a PR in before this weekend.  If you don't see a PR from me by Friday, probably best to try and tackle it yourself -- time permitting, of course.

**Comment by MrJoy** [comment]
Ok, PR provided.  https://github.com/actgardner/gogen-avro/pull/108

**Comment by actgardner** [comment]
Thanks for the PR, merged #108
