### ISSUE TITLE
generated code is out of sync

### ISSUE THREAD

**Issue by rogpeppe** [actgardner/gogen-avro#109]
I ran the following commands:

    git clone git@github.com:actgardner/gogen-avro
    cd gogen-avro
    go install ./gogen-avro
    go generate ./...

The generated code in `container/avro` changes a lot and won't compile (it ends up with a circular import loop):

```
$ go install ./container
can't load package: import cycle not allowed
package github.com/actgardner/gogen-avro/container
	imports github.com/actgardner/gogen-avro/container/avro
	imports github.com/actgardner/gogen-avro/container
```

**Comment by actgardner** [comment]
Sorry, yeah I removed the flag for generating container code so all structs get container-writing methods by default. Consequently the generated code in the container package .... depends on the container package. I'll fix this up and do a patch release.

**Comment by actgardner** [comment]
v6.3.1 is out now, this re-adds the container flag and commits newly-generated versions of the `container/avro` files generated with the current release.
