### ISSUE TITLE
support for single object encoding

### ISSUE THREAD

**Issue by rogpeppe** [actgardner/gogen-avro#111]
The specification defines a [single object encoding](https://avro.apache.org/docs/1.8.2/spec.html#single_object_encoding) format. It would be useful if gogen-avro could support that. This would also require support for [canonical schemas](https://avro.apache.org/docs/1.8.2/spec.html#Transforming+into+Parsing+Canonical+Form).

**Comment by actgardner** [comment]
This is a great feature request, unfortunately I haven't had a lot of time to work on the feature backlog for this project lately. I'd be happy to review a pull request to add this though.

**Comment by actgardner** [comment]
I merged some code in `schema/canonical` to support computing canonical schemas and the Avro 64-bit CRCs per the spec. It'd be great if you could try it out. It would probably benefit from being wrapped in a Writer interface.

**Comment by actgardner** [comment]
This should be complete in v6.5.0 - the soe package provides single-object encoding according to the spec. As always bug reports and requests for improvements are welcome!
