### ISSUE TITLE
Generate avro file from golang struct

### ISSUE THREAD

**Issue by maeglindeveloper** [actgardner/gogen-avro#118]
Hi everyone !

I'm new in avro field, and I would like to generate my schema file from my golang struct. 
For instance, having a **user.go** file (including my **User** struct) would generate the **user.avsc** file. Is it possible using gogen-avro ? because I don't see any way for that (but I might have wrong 🌊 ).

Maybe it is not possible since it is not "relevant" to generate, from your core code, a transport layer ?

Thanks in advance ! 👍  @actgardner 

**user.go**
```
type User struct {
	Firstname string `avro:"firstName"`
	Lastname  string `avro:"lastName"`
}
```

**user.avsc**
```
{
  "type": "record",
  "name": "User",
  "fields": [
    {
      "name": "firstName",
      "type": "string"
    },
    {
      "name": "lastName",
      "type": "string"
    }
  ]
}
```

**Comment by rogpeppe** [comment]
FWIW I'm working on an Avro package that allows that: https://github.com/heetch/avro.

Here's an example of it in action: https://play.golang.org/p/IyAC2si6rjh

**Comment by maeglindeveloper** [comment]
thanks @rogpeppe ! I will have a look at it ;)

**Comment by actgardner** [comment]
Hey @maeglindeveloper, this tool isn't really intended to generate Avro schemas from Go structs, but I'm glad @rogpeppe was able to help you. I'm going to close this issue.
