### ISSUE TITLE
Preserving order of json keys for Schema() (To use with Confluent Schema Registry)

### ISSUE THREAD

**Issue by joshivinay** [actgardner/gogen-avro#126]
Json keys defined in an avsc schema string do not maintain their key ordering when returned from the Schema() method. This creates an issue when working with the Confluent Schema Registry. 
The schema registry hashes the original schema string and uses that hash to register the schema with the schema registry. 

When consuming from Kafka, if we use the schema string returned from the Schema() function, the order of the keys in the json map changes, the hash value changes and the schema cannot be found in the registry. Here is an example of what happens:

Original schema `{"X": 1, "A": 0, "B": "3"}` . The hash is created based on this string. 
The schema which shows up in the generated gogen-avro object {"A":0,"B":"3","X":1}

Since the original schema string doesn't match the one generated by Schema() method, we will never be able to talk to schema registry. 

In the namespace TypeForSchema() and the record Schema() function, the key ordering of the json keys needs to be maintained.

**Comment by actgardner** [comment]
Hey @joshivinay, I've been looking at this as part of https://github.com/actgardner/gogen-avro/issues/111, which would add canonical schema forms and fingerprinting. I think that will solve your issue.

**Comment by actgardner** [comment]
I actually merged support for canonical schemas tonight in v6.4.0, can you try it out and give any feedback in #111? Thanks!
