### ISSUE TITLE
Writing header in container.NewWriter 

### ISSUE THREAD

**Issue by alejandro-falkowski-gelato** [actgardner/gogen-avro#131]
Currently the solution writes a header just before returning a new writer as can be seen here https://github.com/actgardner/gogen-avro/blob/master/container/writer.go#L71

When using pipes in go https://golang.org/pkg/io/#Pipe this operation blocks unless you create the writer in a goroutine. It would be better to not write it in the NewWriter function and just do it the first time when one calls WriteRecord.

Look forward to hearing your toughts.

**Comment by actgardner** [comment]
Doing it lazily on the first write seems like a simple change and I don't see any downside, I'd be happy to accept a PR.

**Comment by actgardner** [comment]
This should be resolved in the newest release (v6.5.0). Thanks for reporting it!

**Comment by alejandro-falkowski-gelato** [comment]
@actgardner when will this be released?

**Comment by actgardner** [comment]
It should be available right now.

**Comment by alejandro-falkowski-gelato** [comment]
Thanks!
