### ISSUE TITLE
issue with new update

### ISSUE THREAD

**Issue by Arnold1** [actgardner/gogen-avro#135]
hi,

after using the v7 update I noticed ```func SetDefault(i int)``` doesn't initialize the fields any more (for the same Avro file):

before (v6):
```
case 7:
		r.bla_id = NewUnionNullLong()
		return
```

now (v7):
```
case 7:
		r.bla_id = nil
		return
```

I'm asking because initializing > 100 fields by hand is a lot of work...

cc @actgardner

**Comment by actgardner** [comment]
In the new version `nil` unions mean `null`. This is a change from 6.x where you had to explicitly set the UnionValue to the null type. This is the correct behaviour.

**Comment by Arnold1** [comment]
@actgardner can you give an example what you mean?

**Comment by actgardner** [comment]
The example you posted is `NewUnionNullLong()`, the first type is `null` so the default must be `null`. So `SetDefault` is correctly setting the pointer to `nil` because in v7 `nil` represents a `null` value in a union. Do you have an example of a field where the default isn't `null` where it's not being initialized?

**Comment by Arnold1** [comment]
all of my fields have default with null...

**Comment by actgardner** [comment]
If your default is null you do not need to initialize the structs in v7.

**Comment by Arnold1** [comment]
you mean I don't need SetDefault but only the following?
```
demoStruct.bla_id = avro.NewUnionNullLong()
demoStruct.bla_id.UnionType = avro.UnionNullLongTypeEnumLong
demoStruct.bla_id.Long = *winNotice.BlaID
```

**Comment by actgardner** [comment]
Correct. If you know the default is null for every field, you no longer need to call `SetDefault`.

**Comment by Arnold1** [comment]
ok. also when I look at my go.mod file:
```
	github.com/actgardner/gogen-avro v6.5.0+incompatible // indirect
	github.com/actgardner/gogen-avro/v7 v7.0.0
```

why I still see v6.5.0?

**Comment by actgardner** [comment]
You can try manually removing it. If that doesn't work some code is referring to the import without the major version at the end.

**Comment by adamtabrams** [comment]
@actgardner I'm having a similar issue in my go.mod file. I'm pretty sure it's because the generated code has imports that don't specifically reference v7. For example:
```
package model

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)
```
I think these are supposed to explicitly import `"github.com/actgardner/gogen-avro/v7/..."`

**Comment by actgardner** [comment]
Thinking about it, there's at least two scenarios where one might find generated code with the old import path:

- the CLI tool hasn't been updated to v7
- there are old, unused generated files committed to git

I'm going to close this issue out since it seems to be solved.
