### ISSUE TITLE
Incompatible types error for field with array of records

### ISSUE THREAD

**Issue by rgalus** [actgardner/gogen-avro#137]
When schema contains field with array of records that are the same but different in name `compiler.CompileSchemaBytes` is returning Incompatible types error.

It works when using gogen-avro version before this commit https://github.com/actgardner/gogen-avro/commit/fe7b2b3e6e3176aa9fd2c464609723b73902f747

**How to reproduce**
Clone the repo https://github.com/rgalus/gogen-avro-issue and run `go run ./issue`

Result:
```
Incompatible types by name: &{foo 0xc0000e0000} &{bar 0xc0000e01c0}
```

Edit:
Here's the schema
```
{
    "type": "record",
    "name": "DemoSchema",
    "fields": [
        {
            "name": "data",
            "type": {
                "type": "array",
                "items": [
                    {
                        "type": "record",
                        "name": "foo",
                        "fields": [
                            {
                                "name": "id",
                                "type": "string"
                            }
                        ]
                    },
                    {
                        "type": "record",
                        "name": "bar",
                        "fields": [
                            {
                                "name": "id",
                                "type": "string"
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

**Comment by actgardner** [comment]
Hi @rgalus - this was a change to bring us closer to the Avro spec. Under (https://avro.apache.org/docs/current/spec.html#Schema+Resolution), only schemas with the same unqualified name are considered to match:

> both schemas are records with the same (unqualified) name

The issue at #112 talks about adding a flag to support evolution with differently-named records. I'd be open to merging a PR that added such a flag.

**Comment by rgalus** [comment]
Hi @actgardner - I've read the other issue and created PR accordingly to discussions

**Comment by actgardner** [comment]
Going to close this issue since lax name support has landed, thanks for the report and the PR!
