### ISSUE TITLE
Round trip failure - wrong union type decoded

### ISSUE THREAD

**Issue by markfarnan** [actgardner/gogen-avro#144]
Using GO 1.14  and gogen-Avro V7, latest from Master.

When attempting to round-trip a schema containing a large union,  the deserializer is returning a different  item in the union. 

Specifically, the input is 'bytes'   []byte,   and the return is string. 

I have created and attached a standalone  Test, all generated files, and all schemas applicable. 
Note: This is a subset of a much larger set of Schemas we use for an open standard.   I am not able to change the schema design. 

The test is in the file roundtripfail_test.go

The complex union is DataValue, and it fails when trying to use "bytes".   
```
{
	"type": "record",
	"namespace": "Energistics.Etp.v12.Datatypes",	
	"name": "DataValue",
	"fields": 
	[
		{"name": "item",
			"type": [
				"null",
				"boolean",
				"int",
				"long",
				"float",
				"double",
				"string",
				"Energistics.Etp.v12.Datatypes.ArrayOfBoolean",
				"Energistics.Etp.v12.Datatypes.ArrayOfInt",
				"Energistics.Etp.v12.Datatypes.ArrayOfLong",
				"Energistics.Etp.v12.Datatypes.ArrayOfFloat",
				"Energistics.Etp.v12.Datatypes.ArrayOfDouble",
				"Energistics.Etp.v12.Datatypes.ArrayOfString",
				"bytes"
			] 
		}
	]
}
```

Also attached, output.txt which contains some debugging lines, and the compiler debug. (which is enabled in the test already). 

I tried tracing the deserializer to see what is going on, but didn't get anywhere. 

Concerned about the last few lines of the Compiler output. 
237:	|  eval_equal(0)
238:	|  cond_jump(223)
239:	|  jump(230)
240:	exit()
241:	return()
Error 1:	Unsupported type for union   **<---- ??**

[avtest.zip](https://github.com/actgardner/gogen-avro/files/4637353/avtest.zip)
[output.txt](https://github.com/actgardner/gogen-avro/files/4637355/output.txt)

Blocking issue for me currently, so hope someone is able to assist !.

**Comment by markfarnan** [comment]
So, looking at the dump, I think I see the error in the program. 
the ItemUnionEnum for the 'bytes' type is 13

As it loops thru the Possible enums, it gets to:
  44:	|  eval_equal(13)
  45:	|  cond_jump(134)

Then
134:	|  set_long(6)            <-------------- Shouldn't this be 13 ?    
135:	|  set(long)
136:	|  enter(6)
137:	|  |  read(bytes)
138:	|  |  set(bytes)
139:	|  exit()

It seems to set a value to 6, then loads the 'string' from the Get function
	case 6:
		return &types.String{Target: (&r.String)}

rather than:
	case 13:
		return &types.Bytes{Target: (&r.Bytes)}

I can't see in the compiler where it is getting these numbers from.

**Comment by actgardner** [comment]
This is by design, the Avro schema says:

> To match, one of the following must hold:
> ... the writer's schema may be promoted to the reader's as follows: ... bytes is promotable to string

and 

> if both are unions:
The first schema in the reader's union that matches the selected writer's union schema is recursively resolved against it. if none match, an error is signalled.

In other words, a union of `[bytes, string]` should always deserialize to `bytes`, because it's the first schema in the reader's union that matches the writer's union, even if the writer's union schema was `string`. This is true for `[string, bytes]` as well (it'll always be `string`).

Now despite what the spec says, the Java implementation is usually taken as canonical and I *think* they special-case this so a union where primitives match acts the way you'd expect. I can take a look at special-casing this here as well.

In the meantime, Avro and Golang both treat `[]byte` and `string` exactly the same so you're not losing any data due to this. You should be able to use the output as-is unless there's a specific reason to know it's a byte array versus a string for your purposes.

> Concerned about the last few lines of the Compiler output.
> 237: | eval_equal(0)
> 238: | cond_jump(223)
> 239: | jump(230)
> 240: exit()
> 241: return()
> Error 1: Unsupported type for union <---- ??

The last line is the error table for the program, it maps exit codes to error strings. If the union value was unsupported the program would fall through to a case where it would exit with that code. It doesn't indicate an error in compilation.

**Comment by markfarnan** [comment]
Thanks for the quick response. 

I think I see where its doing this in the compile 

compileType()
 writer:
 &{{bytes Bytes []byte vm.WriteBytes bytes}}
---
reader: &{{string String string vm.WriteString string}}
---

As we are using the same reader and writer schema's in our standard,  the expectation is exact round-tripping.  (We have enough problems with  dialects between different companies !). 

I'm currently writing the Go dev-kit for the standard and suspect it will be very confusing if data expected as bytes, comes back as a string. 

For reference, I'm not sure on Java, but the C#  one is returning exact matches where it can with these schema.  From what can see,  It only promotes if one is missing,  i.e.  if the writer wrote bytes, but the reader union doesn't have bytes, it can promote up to string.   Currently if I send it bytes,  It reads it as bytes I'm told.

I agree no data is lost, it is more a matter of where to find it programatically.     
This DataValue type is used extensively for streaming mealtime data. (high speed, time series data). 
In other parts of the Spec, it lists what the expected data type of the data will be,  by field type.  

So for example, if company A sends some data as bytes,   and lists it in metadata as bytes,  the receiver is going to have to understand the promotion rules, and know to look in multiple places, rather than just read it.   

I'll need to check if our DataValue union could potentially suffer from other promotion problems.

**Comment by markfarnan** [comment]
Re-reading the Avro spec, it only indicates it MAY promoted. 

  I would propose that it shouldn't be promoting where an exact match is available,  but only should do as a secondary process where it can't find an exact match between reader and writer schema. 

Perhaps as a flag on the compiler ?

**Comment by actgardner** [comment]
I'm fine to make exact matching primitives the default behaviour, I'm just not sure of the timeline. I may have time this weekend to implement it.

**Comment by markfarnan** [comment]
Awesome.    I've worked around it for now.

**Comment by actgardner** [comment]
@markfarnan This should be fixed on master now.

**Comment by markfarnan** [comment]
Great !   Appreciated.  Will test

**Comment by markfarnan** [comment]
Appears to work fine,  thank you. 
Fixed.
