### ISSUE TITLE
JSON-encode unions with fully-qualified type names

### ISSUE THREAD

**Issue by actgardner** [actgardner/gogen-avro#156]
The spec is not explicit, but other avro libraries encode the fully-qualified name of a type into the key when JSON-encoding a union. We should do the same.

**Comment by samuelhewitt** [comment]
When using gogen-avro v7 generated structs for union type, there is an issue in combination with [linkedin/goavro](https://github.com/linkedin/goavro/blob/9f4e906150da20936a04d07bc0bc4d3f7c28bf56/union.go#L127) and [apache-pulsar](https://github.com/apache/pulsar-client-go/blob/5fb7f55939e6f4ec28126339b22a6b4018c0f2fa/pulsar/schema.go#L180-L192).

The pulsar client code Encode uses three steps to get the binary data, first marshal the struct to json, then json -> native, which uses json field names as the codec key. In the case of unions, the codec key is `namespace.name` but the json textual representation field is just `name`.

I am hopeful that switching to the fully-qualified name (`namespace.name`) will fix this and will be testing it out via the v8-beta branch
https://github.com/actgardner/gogen-avro/commit/f02e44d6690748236c5e5af314b5be7c00434361

I'm assuming the commit will fix the issue, so I'm interested if there is there a timeline for a v8 release?

**Comment by actgardner** [comment]
@samuelhewitt This should be fixed in the 8.0 release I just cut, feel free to reopen this issue if it isn't!
