### ISSUE TITLE
[feature request] [generic package] Add Avro Schema Generation from Go map[string]interface{}

### ISSUE THREAD

**Issue by AtakanColak** [actgardner/gogen-avro#160]
Hello, thank you for this library. I couldn't find a way to generate Avro Schemas from Go during runtime so I started working on it as a wrapper package at [my repository](https://github.com/AtakanColak/kafkavro). I saw addition of a generic package as beta, so I thought maybe I could add this functionality to the generic package in this repository instead. Just let me know of your thoughts and if it is suitable I can start working on it.

Reason why I want to do it for map[string]interface{} is it is faster and simpler than reflect and is a superset of structs. So anyone can use [structs](https://github.com/fatih/structs) or their custom implementations with a map.

**Comment by actgardner** [comment]
Hi @AtakanColak! This seems like an interesting project (generating Avro schema definitions from Go structs) but I don't think it's a good fit to add to gogen-avro. Thanks for the suggestion though :)
