### ISSUE TITLE
Question: Default values for record creation

### ISSUE THREAD

**Issue by matlockx** [actgardner/gogen-avro#165]
We recently switched from an older version to the latest release and found out, that New<Record>() does not set the defaults anymore. We used that everywhere during record creation for kafka events so my question is now: is there a way to achieve that again with the current release, cause i do not see any.

**Comment by actgardner** [comment]
Hi @matlockx, I've just released v8.0, one of the changes is that the default values are set for new records in the constructor again. Let me know if you have any issues!

**Comment by matlockx** [comment]
:+1: lgtm

**Comment by matlockx** [comment]
thanks
