### ISSUE TITLE
unions with different type order panic

### ISSUE THREAD

**Issue by rgalus** [actgardner/gogen-avro#166]
The issue happened when migrating from v7 to v8. Looks like when 2 fields has same union but with different order in the schema it returns an error.

Schema:
```json
{
	"type": "record",
	"name": "record_v1",
	"fields": [
		{
			"name": "foo",
			"type": ["null", "string"]
		},
		{
			"name": "bar",
			"type": ["string", "null"]
		}
	]
}
```

Fixtures:
```
[
    {
        "foo": {
            "string": "foo_string"
        },
        "bar": {
            "string": "bar_string"
        }
    }
]
```

Returns an error:
```bash
Panic at pc 17 - Unable to assign string to null field (set(string))
```

Test that reproduce issue:

https://github.com/rgalus/gogen-avro/commit/b284c619deaa93ff8f63730d9c1bda3249b672f9

**Comment by actgardner** [comment]
Hey @rgalus, thanks for the very detailed and clear bug report! This was pretty simple to resolve but it involved changing the name of the type generated for unions containing null, so I've cut a new major release (v9) to reflect that breaking change. Let me know if you run into any more issues :)
