### ISSUE TITLE
enum default values are not used

### ISSUE THREAD

**Issue by puhlenbruck** [actgardner/gogen-avro#167]
The current behaviour of reading enums does not match the [Avro spec for schema resolution.](https://avro.apache.org/docs/current/spec.html#Schema+Resolution)

> if both are enums:
if the writer's symbol is not present in the reader's enum and the reader has a default value, then that value is used, otherwise an error is signalled.

The actual behaviour is to read the encoded int value as is, without checking to see if it is a valid enum value.  The generated `String()` method of the enum will return `"unknown"` if the int is not one of the enum values.  This can happen when reading an avro written with a newer schema that has added symbols to the enum.  What should happen in this case is the default value from the reader's enum is used, and if there is no default we should panic.

I've created a small example repo demonstrating the problem: https://github.com/puhlenbruck/gogen-avro-enum-default-example

**Comment by actgardner** [comment]
Hi @puhlenbruck! Thanks for the bug report. Looking at the spec I think there's actually a few things we're doing incorrectly with enum evolution - they should be resolved by symbol name and not numeric value, such that you could re-order the symbols and they would deserialize correctly between schema versions. 

I don't have the bandwidth to tackle this immediately but in the next few weeks I'll revisit the enum behaviour and do a minor release with a fix.

**Comment by puhlenbruck** [comment]
Thanks for taking a look!  I noticed that as well looking a bit closer.  Using the default values shouldn't be too difficult, just validating in the generated `SetInt` could do it, but handling by symbol (allowing reordering) could be more challenging since it would mean finding the symbol of the index in the writer then finding the index of the same symbol in the reader.  The current `compileEnum` implementation is very simple and just reads the encoded value as is.
