### ISSUE TITLE
Generated constructor code calls NewUnionNull*() which is overwritten by nil

### ISSUE THREAD

**Issue by i7tsov** [actgardner/gogen-avro#178]
I've noticed some weirdness in the generated code:

```go
func NewSample() Sample {
	r := Sample{}
	r.Number = 0
	r.NestedArray = NewUnionNullArrayNested()

	r.NestedArray = nil
	r.Mapping = NewUnionNullMapString()

	r.Mapping = nil
	return r
}
```

Avro schema contains unions of null&array and null&map.
The result of `NewUnionNullArrayNested()` is instantly overwritten with nil (which is the default value for the field), allocating unnecessary memory on the heap.
As far as I can see, there are no side effects of `NewUnionNullArrayNested()` function.

```go
func NewUnionNullArrayNested() *UnionNullArrayNested {
	return &UnionNullArrayNested{}
}
```

Is that intended?

**Comment by actgardner** [comment]
Hey @i7tsov, can you post the Avro schema that produces this code?

**Comment by actgardner** [comment]
@i7tsov I've fixed this so that when the union field's default is null, the record constructor skips instantiating the struct.
