### ISSUE TITLE
Handling schema compatibility

### ISSUE THREAD

**Issue by mremond** [actgardner/gogen-avro#31]
Is the parsing lib able to support parsing content generated with different schema, assuming the Avro schema compatibility rules are properly applied ?

For example, adding a field with a default value should not break schema compatibility.

I made some test with it, but I am hitting EOF error.

For example, here is a possible acceptable change:
1. Add a field at the end of your structure in new version, with a default value.
2. When you read an old structure with the new schema and hit EOF, if there is default value to apply, they should be applied (without error).
3. Reading a new structure with an old schema should be just fine as the new field at the end will be ignored.

Are my assumptions correct ?

**Comment by mremond** [comment]
For the record, I shared my experiments in this repository: https://github.com/mremond/avro-compat-test

**Comment by alanctgardner** [comment]
Sorry this isn't documented more clearly: so far we don't support any schema evolution - there's an assumption that the writer and reader schemas are the same. This is the big change that has held up reading container files.

Avro is kind of unique in how it handles schema evolution - the readers always need to have the writer schema. This is different from a tagged format like protobuf, where you can provide a single reader schema and it'll pull out relevant fields, infer defaults for missing fields, etc. Avro schema evolution allows for fields to be re-ordered, field types to change, etc. so it's a significant undertaking to implement here. The full spec is [here](https://avro.apache.org/docs/1.8.1/spec.html#Schema+Resolution).

Do you mind if I ask about your use case? Are you writing the records to disk or sending them over the wire? You could potentially encode the records like `<schema version> <Avro encoded record>`, and implement the logic in your readers to parse out the schema version and use the correct decoder.

**Comment by karrick** [comment]
@alanctgardner, I've been tossing this schema evolution issue as well in my goavro rewrite at https://github.com/karrick/goavro.

I'm not quite sure how the schema is supposed to evolve. Basically the reader would have to have both the original schema used to write the Avro binary blob, along with the new schema.

I've tried to capture the use case of migrating schemas using this `arw` utility, but I'm not sure whether it would address anyone's concerns.

https://github.com/karrick/goavro/blob/master/examples/arw/README.md

In the meanwhile, curious what you think.

**Comment by mremond** [comment]
Hello Alan,

Thanks for your feedback. My use case is as follow. I am replacing existing code that is using Avro on the Wire (through Kafka) and in database to store large chunk of information.
Schema compatibility is done by using schema registry and trying to find the best schema to use.

What I have started doing is to trying writing a static schema registry that can be embedded in application code to try to fall back to the best deserializer version. It will be up to the application code to map it to the best approaching one.

The code will be on top of gogen-avro. I will release it when I have something working.

Regarding gogen-avro, what I think could help is trying to fill the blank when reading an older Avro buffer, that is if there is missing field at the end, use default value to try finishing the stream. I assumed that schema evolution with default fields can only be done if those fields are added at the end, so the case will be pretty limited.

**Comment by karrick** [comment]
@mremond, our use case at LinkedIn is very similar. Kafka prefixes each Avro blob with a schema ID, which is used to download a schema from a schema registry service. Once we have the schema JSON, we compile a goavro.Codec on the fly to decode the remaining Avro blob and pass the native datum off to the next stage of the process.

I've simplified it a little because we actually maintain a memoized cache of schema IDs to the compiled goavro.Codec, so we only need to download and compile each schema once.

**Comment by mremond** [comment]
@karrick thanks for the update :)
To be sure I understand it well, you use gogen-Avro to statically compile your codec on the fly, codec being static is very efficient. Am I right ? How do you load the compiled binary in Go dynamically ? Do you use plugins ?

**Comment by karrick** [comment]
No I use https://github.com/karrick/goavro because it was designed to compile and use schemas on the fly when they are not known ahead of time.

I am not trying to detract against this library. If you know the schema ahead of time this library can create highly performant code. But if you don't always have your schema at build time, goavro sounds like a better fit for your particular needs...

**Comment by alanctgardner** [comment]
@mremond I've been working on a version of gogen-avro that would support reading a compatible schema into a generated struct.

The branch is here - right now it supports the "new fields with default values" use case you mentioned: https://github.com/alanctgardner/gogen-avro/tree/evolution

An example of how to use the new API is in this test case: https://github.com/alanctgardner/gogen-avro/blob/evolution/test/evolution/schema_test.go

**Comment by mremond** [comment]
Many thanks, @alanctgarner

This is great news. I will give it a try and share my feedback / tests.

Thanks again !

**Comment by catlittlechen** [comment]
@alanctgardner  I have read your codes on evolution branch. I think you can return the sturct and error when error is found. As a result, I can deal with the errors. When I find the error is EOF,  I can choose to ignore it, and get the struct. Balabalabla....

**Comment by burdiyan** [comment]
Are there any news about that? What's the current state of it? What needs to be done to implement the feature?

Schema evolution is something that we really need for our project, and we don't want to use linkedin/goavro because of the lack of type safety, and we still want to generate code, but be able to read backward compatible Avro records.

If I'm not mistaken, Java code generation for Avro allows for that.

I understand that this may be a breaking change for gogen-avro, but maybe it worth it.

**Comment by burdiyan** [comment]
@actgardner do you remember at which point your WIP implementation were left off? Any roadblocks, or some things to take into account?

**Comment by mremond** [comment]
Just for the record, when I tested the branch, it was working well for me. I think it was a relevant change.

**Comment by actgardner** [comment]
Hey, sorry for the lack of updates. The issue with the old branch was mostly that it's bit-rotted now relative to master, so I think it's easier to start from scratch than to rebase.

I'll take another crack at it this week and see if I can get an up-to-date branch with a framework where someone could fill in some of the blanks.

**Comment by javierholguera** [comment]
@actgardner any news on this? We are planning to use your library with a similar use case (Kafka + Schema Registry) and having support for evolution is critical for us.

Thanks!

**Comment by johndww** [comment]
@actgardner I'm also looking at using this library and have a similar use case. The producer will be upgrading it's schema at a slightly different time from the consumers which means there is a period of time where the old schema must be read on the consumer.

**Comment by caevv** [comment]
+1

**Comment by actgardner** [comment]
Hi! I know it's been a while, I have a beta branch which now supports schema evolution: https://github.com/actgardner/gogen-avro/tree/gadgt

Please try it out and let me know if there any issues or deviations from the spec. Thanks!
