### ISSUE TITLE
Option to disable UnionNull... struct  code generation

### ISSUE THREAD

**Issue by jozef-slezak** [actgardner/gogen-avro#40]
Hello, I would like to propose a tweak (a code generation option) that would simplify the amount of generated structures just by using pointers in following situations:
1. when a null and primitive type is used, for example ["null", "int"]
2. when a null and record is used ["null", { "type" : "record" ...

Above tweaks are explained by using following examples:

1. The first tweak can be explained on an example mentioned in existing README.md

Instead of:
```
type EnclosingRecord struct {
	Field UnionNullInt
}

type UnionNullInt struct {
	// All the possible types the union could take on
	Null               interface{}
	Int                int32
	// Which field actually has data in it - defaults to the first type in the list, "null"
	UnionType          UnionNullTypeEnum
}
```

I am proposing: let's generate just pointer to primitive type - in this particular example it would be: 
```
type EnclosingRecord struct {
	Field *int
}
```

2. The second tweak:

Instead of:
```
type EnclosingRecord struct {
	Field UnionNullRecordXY
}

type UnionNullRecordXY struct {
	// All the possible types the union could take on
	Null               interface{}
	Int                *RecordXY
	// Which field actually has data in it - defaults to the first type in the list, "null"
	UnionType          UnionNullTypeEnum
}
```

I am proposing: let's generate just pointer to record type - in this particular example it would be: 
```
type EnclosingRecord struct {
	Field *RecordXY
}
```

What do you think? If it makes sense to you, I could provide a pull request.

Thanks

Jozef

**Comment by jozef-slezak** [comment]
Perfect, I will provide PR.

**Comment by tzachshabtay** [comment]
@jozef-slezak are you working on this?
This will be very useful for us.
Thanks.

**Comment by nichochar** [comment]
+1 This seems like a really nice quality of life feature

**Comment by actgardner** [comment]
@nichochar @tzachshabtay @jozef-slezak

This will be the new default behaviour in the next major release - unions that contain `null` can be set to `nil` and serialize/deserialize appropriately. The code is currently on master, if you want to test it out before I cut the official release and offer any feedback.

**Comment by tomasfabian** [comment]
Hi @jozef-slezak @actgardner , 
how can we switch the **gogen-avro** to generate a `*string` type instead of a `UnionStringNull`, please? I didn't find a flag for it.

Thank you!
