### ISSUE TITLE
Generated files are executable

### ISSUE THREAD

**Issue by tv42** [actgardner/gogen-avro#42]
Go source files should not have execute access.

```
tv@dark ~/z$ ls
schema.avro
tv@dark ~/z$ cat schema.avro 
{
     "type": "record",
     "name": "A",
     "fields": [
       { "name": "name", "type": "string" },
       { "name": "birthday", "type": "long" },
       { "name": "phone", "type": "string" },
       { "name": "siblings", "type": "int" },
       { "name": "spouse", "type": "boolean" },
       { "name": "money", "type": "double" }
     ]
}
tv@dark ~/z$ gogen-avro . schema.avro 
tv@dark ~/z$ ls -l
total 4
-rwxrwxr-x 1 tv tv  773 Mar 29 15:02 a.go*
-rwxrwxr-x 1 tv tv 5224 Mar 29 15:02 primitive.go*
-rw-rw-r-- 1 tv tv  346 Mar 29 15:02 schema.avro
tv@dark ~/z$ 
```

This is incorrect:
https://github.com/actgardner/gogen-avro/blob/263625dd5238e3094231add01a1ae927ecdfe63a/generator/file.go#L53

That's a bitmask you're passing in, you're trying to give all possible access to the file, only tamed by the umask. Pass in 0444 or something like that, instead.

**Comment by actgardner** [comment]
Thanks for raising this, this is a dumb mistake that I'll fix in the next couple days!

**Comment by actgardner** [comment]
This is fixed on master now, files are generated with 0440 permissions.
