### ISSUE TITLE
Make `primitive.go` independent of *.avsc files

### ISSUE THREAD

**Issue by JensRantil** [actgardner/gogen-avro#43]
I just had a package with a single file containing
```
package avro

//go:generate $GOPATH/bin/gogen-avro --containers . users.avsc
//go:generate $GOPATH/bin/gogen-avro --containers . items.avsc
```
When running `go generate`, `primitive.go` was overwritten by `//go:generate $GOPATH/bin/gogen-avro --containers . items.avsc` which lead to `writeUser(...)` and `readUser(...)` not being available. After some debugging I realized 1) that

```
//go:generate $GOPATH/bin/gogen-avro --containers . *.avsc
```

doesn't work and 2) I had to do

```
//go:generate $GOPATH/bin/gogen-avro --containers . users.avsc items.avsc
```
.

Above said, I would have avoided having to debug this if a new `go:generate` would not overwrite a previous one. My proposal is that all user-specific functions are put in the `user.go`-generated file instead.

Thoughts?

**Comment by actgardner** [comment]
Sorry for the slow reply! Due to the structure of this project this would be kind of time-consuming to implement. I will add the work-around to the README so it's clear to new users that this is possible.

**Comment by actgardner** [comment]
README is updated!
