### ISSUE TITLE
Generation is type ordering dependent

### ISSUE THREAD

**Issue by JensRantil** [actgardner/gogen-avro#47]
Schema
```
{
    "type": "record",
    "name": "Account",
    "fields": [
        {"name": "accountnumber", "type": ["null", "string"]},
        {"name": "name", "type": ["string", "null"]},
    ]
}
```
yields
```
type Account struct {
        Accountnumber        UnionNullString
        Name                 UnionStringNull
}
```
Since `type` really is a set, I expect `Accountnumber` to have the same type as `Name`, but they differ.

**Comment by actgardner** [comment]
The order of the types in the union impacts the serialization and deserialization of the field, so we need to track it somehow - those fields get written on the wire differently even though they seem to represent the same type. While I agree this is an implementation detail to end users, I don't have a better solution for how to track this data right now. I'm open to a PR that fixes this but remains complaint with the spec.

**Comment by actgardner** [comment]
I'm going to close this, it's unlikely to change - I was just working on the code to set default values for union fields and the semantics of defaults for Avro unions (default must be the first type) means the different orders actually matter for the generated code. I'm still open to a PR that can handle this while remaining compliant with the spec (there's integration tests for union defaults in a variety of cases now).
