### ISSUE TITLE
container.NewWriter should not accept empty compression codec

### ISSUE THREAD

**Issue by FrancoisWagner** [actgardner/gogen-avro#48]
For now, the container.Writer Factory Method doesn't return any error if one forgets to assign a value to the `codec` parameter. I would expect the method to return an error or assign the `Null` Codec instead. This `codec` parameter mistake/omission can be a bit difficult to troubleshoot, as it causes a `nil pointer` exception into the AvroRecord's `Serialize` method of the record being written.

Proposal:

```go
	if codec == Deflate {
		avroWriter.compressedWriter, err = flate.NewWriter(avroWriter.blockBuffer, flate.DefaultCompression)
		if err != nil {
			return nil, err
		}
	} else if codec == Snappy {
		avroWriter.compressedWriter = newSnappyWriter(avroWriter.blockBuffer)
	// else if codec == Null
        } else {
		avroWriter.compressedWriter = avroWriter.blockBuffer
	}
```

**Comment by actgardner** [comment]
Thanks for reporting this! Defaulting to the null codec sounds reasonable. If you're interested in submitting a PR I'd be happy to merge it, or I can make this fix in a couple days.
