### ISSUE TITLE
Very long type names

### ISSUE THREAD

**Issue by fracasula** [actgardner/gogen-avro#53]
Hi everyone,

First of all thank you for your efforts and for writing this really nice library. I came across it the other day and decided to give it a try so that we could hopefully start using it in production at Foodchain.

So I tried to generate some code out of a schema that we wrote a while ago and I ended up with 2 files that have very long names. More than the file name what concerns me is the name of the types inside which of course are more or less of the same length as the filename ones.

Here's an example:

```go
// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     products-events.avsc
 */

package product_event

type UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdated struct {
	SupplierCreated                *SupplierCreated
	ProductCreated                 *ProductCreated
	ProductAddedToGroupCatalog     *ProductAddedToGroupCatalog
	ProductRemovedFromGroupCatalog *ProductRemovedFromGroupCatalog
	SupplierDetailsUpdated         *SupplierDetailsUpdated
	ProductDetailsUpdated          *ProductDetailsUpdated
	UnionType                      UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum
}

type UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum int

const (
	UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnumSupplierCreated                UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum = 0
	UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnumProductCreated                 UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum = 1
	UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnumProductAddedToGroupCatalog     UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum = 2
	UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnumProductRemovedFromGroupCatalog UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum = 3
	UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnumSupplierDetailsUpdated         UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum = 4
	UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnumProductDetailsUpdated          UnionSupplierCreatedProductCreatedProductAddedToGroupCatalogProductRemovedFromGroupCatalogSupplierDetailsUpdatedProductDetailsUpdatedTypeEnum = 5
)
```

Attached the schema I used to generate the code above and below the `generate.go` file:

```go
package avro

// Use a go:generate directive to build the Go structs for `example.avsc`
// These files are used for all of the example projects
// Source files will be in a package called `example/avro`

//go:generate mkdir -p ./product_event
//go:generate $GOPATH/bin/gogen-avro --package=product_event ./product_event ./../../schemas/products-events.avsc
```

Would there be a way to avoid generating such long names?

Thanks!

[products-events.zip](https://github.com/actgardner/gogen-avro/files/2287803/products-events.zip)

**Comment by actgardner** [comment]
Hey @fracasula, this is an unfortunate side-effect of how we generate the structs for union types - the Union struct's name is a concatenation of all the types in the union. Since your Event record is a wrapper around many types in a union, the union name is very long (and will change and get longer if you add more event types).

I would be open to something like short union names based on `<containing record> + <field>`, which I think should still be unique barring namespacing issues. So in your case we would call this union `EventEventUnion`. I'd put this behind a flag to avoid breaking existing codebases. Is that preferable?

**Comment by actgardner** [comment]
@fracasula I've added a flag on master and cut a release (5.1.0) with a new `--short-unions` flag. This will make the names of union types much shorter, but in some complicated namespaces it risks a collision (where two union types have the same name and different fields), so I'm leaving it off by default for now. Let me know if it fixes your problem!

**Comment by actgardner** [comment]
I'm going to go ahead and close this issue, feel free to reopen it if the new short names don't meet your needs.
