### ISSUE TITLE
Missing package management

### ISSUE THREAD

**Issue by uroshercog** [actgardner/gogen-avro#56]
Can you @actgardner please add something like `dep` to manage dependencies? Right now I'm not certain I have the same ones (I'm assuming this is the main reason most of my tests are failing).

`container_test.go:85: cannot create OCFReader: cannot read OCF header with invalid avro.schema: Record "event" field 1 ought to be valid Avro named type: unknown type name: "string.uuid"
`

**Comment by actgardner** [comment]
I think we figured out this issue didn't have to do with dependencies, but I went ahead and added a dep file to the repo as well.
