### ISSUE TITLE
Does the library support logical types?

### ISSUE THREAD

**Issue by javierholguera** [actgardner/gogen-avro#60]
As defined here: https://avro.apache.org/docs/1.8.2/spec.html#Logical+Types

Will they be ignored and serialize/deserialize as their underlying types (e.g. `timestamp-millis` as a `long`)? Will the same happen for the code generation part?

Thanks.

**Comment by actgardner** [comment]
Hey @javierholguera, sorry for the slow reply! Logical types will be treated as their underlying type, there's no special logic to handle them but the records can be deserialized.

**Comment by actgardner** [comment]
The code generated will be for the underlying type (it'll be an int64 for a timestamp). There's no support for logical types right now. I'd be happy to consider a PR to add support for automatically converting logical types in the generated code.

**Comment by javierholguera** [comment]
Thanks for clarifying. I'm not involved with the project that required this anymore, so I'm happy to close the issue.
