### ISSUE TITLE
Return interface on deserialization

### ISSUE THREAD

**Issue by caevv** [actgardner/gogen-avro#61]
Deserialize should return `container.AvroRecord` so that the function can be passed around on a consumer.

**Comment by actgardner** [comment]
I'm not sure I understand the proposal - you want a generic AvroRecord that you have to downcast at runtime to be able to get the fields?

**Comment by caevv** [comment]
The deserialiser is created like this for example:

```func DeserializeFullName(r io.Reader) (*FullName, error) {
	return readFullName(r)
}```

Instead of returning `*FullName`, return `(container.AvroRecord, error)`

This way I can create a generic function that would accept a deserialiser for any entity, by just running: `deserializer func(r io.Reader) (container.AvroRecord, error)`

**Comment by caevv** [comment]
Bit off-topic, but would be because there is no generator for linkedin
goavro expected native (from and to `map[string]interface{}`).

**Comment by actgardner** [comment]
Sorry, to be clear linkedin/goavro is a totally separate implementation with different goals. I don't expect you to use both, I'm saying goavro is a better fit for your use case.

**Comment by actgardner** [comment]
I'm going to close this issue, if you have further questions feel free to open a new one!
