### ISSUE TITLE
New tag needed

### ISSUE THREAD

**Issue by FrancoisWagner** [actgardner/gogen-avro#62]
A new tag is needed in order to apply the fix https://github.com/actgardner/gogen-avro/pull/58

**Comment by actgardner** [comment]
Hey Francois! I'm sorry this was broken for so long, I think it should be fixed in the v5.2 tag now. 

Since I started working on this project I also found out about https://github.com/twitchtv/retool, which might be helpful? Retool + vendoring should support any SHA from this repo.

**Comment by FrancoisWagner** [comment]
Thanks! I will have a look to `retool` as well.
