### ISSUE TITLE
Evolution branch

### ISSUE THREAD

**Issue by caevv** [actgardner/gogen-avro#63]
Is there a plan to merge evolution branch?
Would be good to support Schema Evolution to have writer and reader Schema on deserialisation.

**Comment by actgardner** [comment]
The evolution branch is fairly far behind and is missing a lot of features, at this point I think we would need to start from scratch.

I'm looking for somebody to help maintain this project and possibly drive development of schema evolution support. I don't have the time to add a big feature for the foreseeable future.

**Comment by actgardner** [comment]
@caevv If you're still interested in evolution support, I have a new branch which is a beta for gogen-avro v6. It includes OCF deserializers and schema evolution: https://github.com/actgardner/gogen-avro/tree/gadgt
