### ISSUE TITLE
Allow globbing the spec files

### ISSUE THREAD

**Issue by artheus** [actgardner/gogen-avro#66]
There seems to be no support for writing glob-patterns like `*.avsc` or `**/*.avsc` when writing the line. Allowing globbing would be a great feature for this code generator.

**Comment by actgardner** [comment]
Usually I would consider this a concern for the shell - if you run this in bash you can use those globs, because bash should expand them. I haven't thought through all the use cases, is there a scenario where you can't use the shell's built-in support for globbing?

**Comment by artheus** [comment]
I am tried to use globbing with the commant directives. That gave me errors.
I will try more and comment with the result in this issue.

**Comment by actgardner** [comment]
Hey! I hope this ended up working for you. I'm going to keep this issue open, if anyone is interested in PRing a patch to add support for filename globbing I would be open to that.

**Comment by actgardner** [comment]
@artheus I added globbing support on master and it will be included in the 6.0 release as well.
