### ISSUE TITLE
Allow adding tags to struct fields

### ISSUE THREAD

**Issue by rocurley** [actgardner/gogen-avro#76]
As of #67, it's possible to add comments to the generated structs. AFAICT, however, it's impossible to add tags. This makes it tricky to use libraries that depend on tags, such as [validator](https://godoc.org/gopkg.in/go-playground/validator.v9). Please consider adding a way to add tags to struct fields, such as:
```
{
  "type": "record",
  "name": "MyRecord",
  "fields": [
    {
      "name": "MyField",
      "type": "string",
      "go_tags": "validate:\"required\""
    },
  ]
}
```
... generates ...
```
type MyRecord struct {
	MyField string `validate:"required"`
}
```

**Comment by jeroenrinzema** [comment]
I am facing a similar issue where we have to share AVRO schemas across different services in our system.

I would like to use this feature to mark field that hold sensitive information (GDPR).

```golang
type User struct {
  FirstName string `sensitive:"true"`
}
```

This way we could define which field need special care, for example to be encrypted.
About the AVRO schema attribute name I do not think that `go_tags` is a good attribute, since it is bound to the language `go`. Maybe an attribute as `tags` or `annotations` is a good alternative?

**Comment by maarek** [comment]
I'll piggyback this issue until deemed to open a new one, but what about extending tags to first auto-generate json marshalling tags on the structs? This would be useful for using the Avro struct with say the kafka rest proxy which expect the kafka input as json along with the schema.

**Comment by actgardner** [comment]
Sorry for the slow replies. Thanks @jeroenrinzema for the PR to add custom tags!

I think a separate issue would make sense to automatically add JSON annotations? I'm open to a  PR on master or the GADGT branch to add it, otherwise I might have time in April to take a look.

**Comment by jeroenrinzema** [comment]
I could modify the PR and include automatic JSON annotations. Should we allow different naming for fields? for ex:

```go
type User struct {
  FirstName string `json:"first_name"`
}
```

**Comment by actgardner** [comment]
I think in order to conform to the Avro spec, the JSON field names have to be the exact Avro field names - even if they aren't snake-case that would be conventional in Avro.

**Comment by maarek** [comment]
@jeroenrinzema What is the convention for the addition of tags in the schema? "go_tags" "GoTags" "goTags"? Avro is fairly loose on their naming convention and each individual defined it as long as it falls within [A-Za-z_] pattern.

Could we pare this down to 1 word to remove ambiguity or handle all variations?

**Comment by actgardner** [comment]
I'm open to just calling it `tags` with the knowledge that it might conflict in the future

**Comment by rocurley** [comment]
I'd weakly advocate for calling it something go-specific: it seems pretty unlikely that your go tags (like `validate` in my original example) will actually be relevant outside the context of go.

**Comment by jeroenrinzema** [comment]
@maarek when writing the proposal did I want to let the name clearly state that the attribute is `go` specific, but agree that we could simplify it. I found a [discussion from 2016](http://apache-avro.679487.n3.nabble.com/custom-attributes-td4033790.html) about the use of custom attributes and think that we could safely name it: `tags`.

**Comment by actgardner** [comment]
The only counter-example I could find is the Java-specific `avro.java.string` being added to the type itself:
https://stackoverflow.com/questions/25118727/how-to-generate-fields-of-type-string-instead-of-charsequence-using-avro

Given that limited example I think it's fine to say `tags` or `avro.golang.tags` if we want to make it more explicitly language-specific.

**Comment by jeroenrinzema** [comment]
I like the use of `avro.golang.tags` but could we maybe shorten it to `golang.tags`?

**Comment by jeroenrinzema** [comment]
I have updated my PR, please take a look

**Comment by actgardner** [comment]
This feature is now on master, is anyone interested in pursuing JSON tags? I would like to merge the gadgt branch this month and make a new major release, but I'd like to get all the tag changes into a minor release first.

**Comment by jeroenrinzema** [comment]
I could pick this up, it would also include refactoring a little bit #77

**Comment by actgardner** [comment]
Yeah I don't mind holding off on a release until both changes (custom tags and automatic JSON tags) are ready to go, if you're interested.

**Comment by jeroenrinzema** [comment]
Let's continue the discussion in #79

**Comment by actgardner** [comment]
Because of the ongoing discussion of how we want to handle JSON encoding (tags versus fulfilling the interface), I've cut the v5.3.0 release on gopkg.in with support for custom tags but not automatic JSON serializing. 

We can continue the discussion of how to handle JSON after I get GADGT merged to master.
