### ISSUE TITLE
Support for standard library MarshalJson([]byte, error) for structure fields

### ISSUE THREAD

**Issue by codeyrk** [actgardner/gogen-avro#82]
From #79 

- Configurable support to add MarshalJSON([]byte, error) during code generation. MarshalJSON is called by the standard library "encoding/json" on all the fields, as per Marshal documentation.
Many other libraries are calling this function internally to convert native struct to JSON.

- Enumerations which are currently returned as numbers instead of string representations can be resolved by above approach. Example generated code:
```go
type ESomeType int32
const (
    ESomeTypeA ESomeType = 0
    ESomeTypeB ESomeType = 1
)

func (e ESomeType) String() string {
    switch e {
    case ESomeTypeA:
        return "A"
    case ESomeTypeB:
        return "B"
    }
    return "unknown"
}

func (e ESomeType) MarshalJSON() ([]byte, error) {
    switch e {
    case ESomeTypeA:
        return []byte("\"A\""), nil
    case ESomeTypeB:
        return []byte("\"B\""), nil
    }
    return []byte("unknown"), nil
}
```
There could be a way reutilize the existing String function.

**Comment by jeroenrinzema** [comment]
@actgardner what is your thought on this?

**Comment by actgardner** [comment]
I commented on #79 but I like this proposal, with the additional caveat that besides enumerations it'll also need to handle unions. I don't have a timeline on when I could implement this but I would be open to PRs, and I'll look at it after GADGT and code cleanup/dependency management for 6.0.

**Comment by actgardner** [comment]
@jeroenrinzema per my comment on #79 this should be resolved on master and will be included in the next release. Testing and feedback would be much appreciated.

**Comment by pri-naik5** [comment]
@actgardner The autogenerated overrided MarshalJson ignores the golang.tags related to "omitempty". Is there a way to configure to use the original MarshalJson method instead? Thanks!
