### ISSUE TITLE
Suppress "SOURCES" comment?

### ISSUE THREAD

**Issue by nickretallack** [actgardner/gogen-avro#84]
When I generate code it adds a comment to every file listing the "SOURCES".  So, every time I add a new file, all existing files are affected.  This creates conflicts when collaborating via git.  Could we omit this comment?

**Comment by actgardner** [comment]
This is a good point, I think it makes sense to eliminate this comment.

**Comment by actgardner** [comment]
Hey @nickretallack, I know this has been open for a while but I did finally add a flag `--sources-comment=false` which you can use to suppress this comment and clean up your diffs. It's currently on master. Thanks for your patience!

**Comment by nickretallack** [comment]
Thank you!
