### ISSUE TITLE
Nested maps are not supported 

### ISSUE THREAD

**Issue by karol-kokoszka** [actgardner/gogen-avro#89]
Seems that because of small bug, it's not possible to generate code for schema with nested map.
I made a fix already with tests, but as no permission for pushing to this repo, it's available here https://github.com/karol-kokoszka/gogen-avro/commit/d84f713550b14e436f86a5b5e84515cf930cb483

**Comment by kishaningithub** [comment]
@karol-kokoszka You can always raise a pull request in github.

**Comment by actgardner** [comment]
Hi @karol-kokoszka! Thanks for the heads up, that fix looks good - can you make a pull request to this repo so I can merge it?

**Comment by karol-kokoszka** [comment]
@actgardner done
