### ISSUE TITLE
New tag for master

### ISSUE THREAD

**Issue by theUm** [actgardner/gogen-avro#92]
As I see that there is lots of new features and approaches in latest master. It would be cool if there where tag with this changes

**Comment by oleksmir** [comment]
The branch (gadgt) which supports schema evolution was already merged. It would be nice to tag new version to start using new feature instead of using direct hash to the latest version.

**Comment by actgardner** [comment]
I've tagged the current head of master as `v6.0.0`. I'm not going to continue supporting `gopkg.in` so you'll need to use dep or modules to version the imported package, plus possibly something like retool to manage the version used to compile your schemas. Let me know how this works for you.

**Comment by theUm** [comment]
Thank you, I'm already using `dep` for now. And thank you for pointing out `retool`, it something I've unknowingly needed :)
