### ISSUE TITLE
Deserialization failed

### ISSUE THREAD

**Issue by proishan11** [actgardner/gogen-avro#95]
Message received from kafka and I am getting an error during Deserialization-

`"Deserialization failed..." error="Runtime error: Unsupported type for union, frame: {false 0 56 0 0 []  false}, pc: 0xc420013bd0"`

**Comment by tzachshabtay** [comment]
Looking at the code, here:

https://github.com/actgardner/gogen-avro/blob/8ba4989fcf94bdb24f2654b27224b90c7ae328b1/compiler/method.go#L286

This error seems to always be added when compiling a union, no matter what. Is that intended?

@actgardner

**Comment by actgardner** [comment]
The compiler is responsible for generating byte code - it generates an error number but that doesn't mean the compiler is raising this error.

Can you post the reader and writer schemas and the data you're trying to deserialize so I can reproduce this issue?

**Comment by tzachshabtay** [comment]
Ah ok, I'm not experiencing the runtime error as the OP, I'm trying to debug some other deserialization issue, so I have enabled logging and saw this error showing up multiple times.. so I guess I can just ignore it, it doesn't mean anything if it's logged without actually being returned as an error?

**Comment by actgardner** [comment]
Same ask, can you provide the reader and writer schemas and the compiler debug output logs?

> so I guess I can just ignore it, it doesn't mean anything if it's logged without actually being returned as an error?

The debug logs from the compiler will include a line about adding the union error to the error table for the deserializer. That's totally harmless debug output. If you get an error like OP with a `PC` and `frame` that's a runtime error.

**Comment by actgardner** [comment]
@tzachshabtay @proishan11 The current master has a few fixes for schema evolution when there are unions involved which may solve your problem. If you get errors in the future feel free to open a new issue including your reader and writer schemas (or reasonable copies without sensitive data) and the debug logs from the compiler. Thanks!

**Comment by proishan11** [comment]
@actgardner I tried the current master but it is still failing. 
Schema used for generation - 

```
{
  "type": "record",
  "name": "intopic",
  "namespace": "service",
  "doc": "service Input",
  "fields": [{
      "name": "url",
      "type": [
        "null",
        "string"
      ],
      "doc": "URL to process",
      "default": null
    },
    {
      "name": "headers",
      "doc": "Headers to be used",
      "default": [

      ],
      "type": {
        "type": "array",
        "items": {
          "name": "intopic.header",
          "type": "record",
          "fields": [{
              "name": "key",
              "type": [
                "null",
                "string"
              ],
              "doc": "Key of the header",
              "default": null
            },
            {
              "name": "value",
              "type": [
                "null",
                "string"
              ],
              "doc": "Value of the header",
              "default": null
            }
          ]
        }
      }
    },
    {
      "name": "next",
      "doc": "Next url to process",
      "deault": [

      ],
      "type": {
        "type": "array",
        "items": {
          "name": "next",
          "type": "record",
          "fields": [{
              "name": "regex",
              "type": [
                "null",
                "string"
              ],
              "doc": "Regex of the url to be processed next",
              "default": null
            },
            {
              "name": "headers",
              "doc": "Headers to be used when crawling the url",
              "default": [

              ],
              "type": {
                "type": "array",
                "items": {
                  "name": "intopic.next.header",
                  "type": "record",
                  "fields": [{
                      "name": "key",
                      "type": [
                        "null",
                        "string"
                      ],
                      "doc": "Key of the header",
                      "default": null
                    },
                    {
                      "name": "value",
                      "type": [
                        "null",
                        "string"
                      ],
                      "doc": "Value of the header",
                      "default": null
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    }
  ]
}
```

Serialization logic -

```
outputMsg := input.NewIn()
outputMsg.Get(0).SetLong(1)
outputMsg.Url.String = link

outputMsg.Headers = consumedMsg.Headers

outputMsg.Next = []*crawlerinput.Next{}

var output bytes.Buffer
err = outputMsg.Serialize(&output)
if err != nil {
    logger.Log.WithError(err).Error("Failed to create output message")
}
```

```
Deserialization logic -
consumedMsg, err := input.DeserializeIn(bytes.NewReader(message.Value[5:]))
if err != nil {
	logger.Log.WithError(err).Error("Deserialization failed...")
	return err
}
```

**Comment by actgardner** [comment]
@proishan11 What's the error you're getting? That code isn't a self-contained example, I can't run it to reproduce the issue.

**Comment by proishan11** [comment]
@actgardner `"Deserialization failed..." error="Runtime error: Unsupported type for union, frame: {false 0 56 0 0 [] false}, pc: 0xc420013bd0"`. This is the error I am getting. I have made a simple hello-world application to show how I am serealizing and deserealizing. Take a look - [https://github.com/proishan11/kafka-hello-world](https://github.com/proishan11/kafka-hello-world). Thanks!

**Comment by actgardner** [comment]
Unless I'm misunderstanding, your writer writes: `<record bytes><schema ID>`, but your reader expects `<schema ID> <record bytes>`. 

You should change `writer.go` line 36 to `out := append(dataBytes, output.Bytes()...)`

https://github.com/proishan11/kafka-hello-world/blob/master/writer/writer.go#L36
https://github.com/proishan11/kafka-hello-world/blob/master/reader/reader.go#L25

**Comment by anishkargaonkar** [comment]
@proishan11 Try changing the [L34 - L36](https://github.com/proishan11/kafka-hello-world/blob/b0b971a5d8196ae383fc4ae6b4d65c7d22b273a0/writer/writer.go#L34) as follows: 
```
dataBytes := make([]byte, 5)
binary.BigEndian.PutUint32(dataBytes, uint32(tempSchemaID))
out := append(dataBytes, output.Bytes()...)
```
It looks like `one extra empty byte` is needed while appending `dataBytes` & `output.Bytes()` to properly deserialize the message .i.e. [`dataBytes` `0` `output.Bytes()`]
