### ISSUE TITLE
Schema evolution- support field aliases

### ISSUE THREAD

**Issue by tzachshabtay** [actgardner/gogen-avro#96]
Looking at the code, I can see that aliases should be supported for record, enum and fixed, but I don't see anything for the other primitives.

To be more concrete, if I have in my old schema (idl):

```
    long some_value;
```

And in my new schema:
```
    long @aliases(["some_value"]) some_new_value;
```

Feeding an old record (with the old writer's schema) to the new reader returns an error:

```
panic: Incompatible schemas: field some_new_value in reader is not present in writer and has no default value
```

I expected it to map the old field name to the new field name due to the alias.

**Comment by actgardner** [comment]
You're correct, we currently don't have support for aliased fields, only aliased complex types. This is an oversight and I'll try and put out a patch shortly to resolve it. Thanks for reporting this!

**Comment by actgardner** [comment]
There's a fix merged to master now, can you confirm it resolves your issue? Then I can tag a new release.

**Comment by tzachshabtay** [comment]
I can confirm, it's working now, thanks :)

**Comment by actgardner** [comment]
I've tagged version 6.1 with these fixes, thanks again!
