### ISSUE TITLE
How should I check for null values?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [actgardner/gogen-avro#97]
Hello,
how am I supposed to check for null values?

I have a `UnionDoubleNull` type but this doesn't work:

```
if elem.CO2reading.Null == nil {
     builder.WriteString(" null")
}
```
it's always null even when value is not null.

**Comment by actgardner** [comment]
The `Type Conversion` section in the README talks about how unions are converted to Go types: https://github.com/actgardner/gogen-avro#type-conversion

If your field is a `UnionDoubleNull`, the `UnionType` field will be `UnionDoubleNullTypeEnumNull` if the field is a null or `UnionDoubleNullTypeEnumDouble` if the field is a double. So your code should look like:

```
if elem.CO2reading.UnionType == UnionDoubleNullTypeEnumNull  {
     builder.WriteString(" null")
} else if elem.CO2reading.UnionType == UnionDoubleNullTypeEnumDouble {
     // Do stuff with elem.CO2reading.Double
} else {
    // Handle the case where the schema evolves and this has an unexpected type besides Null or Double?
}
```

There's an open issue to explore special-casing unions of `[null, <one other type>]` as a pointer to `one other type>` which would be nil if the union is null. It's a pretty common pattern but special-casing those unions would affect a lot of the codebase and nobody has attempted it.

**Comment by invasionofsmallcubes** [comment]
I see. Thank you for the answer.
I have to say, after having read it again, I have to say without having the context of your answer, is not completely clear, probably you could add the example you just posted here.

I you want I'm happy to open a PR to add it to the `README.md`

**Comment by actgardner** [comment]
For sure, if you PR a concrete example in the README (or the examples folder) I think that would be valuable.

**Comment by invasionofsmallcubes** [comment]
Ok, will do.
